call cordova plugin remove org.apache.cordova.geolocation
call cordova plugin remove org.apache.cordova.camera
call cordova plugin remove org.apache.cordova.contacts
call cordova plugin remove org.apache.cordova.file
call cordova plugin remove org.apache.cordova.device
call cordova plugin remove org.apache.cordova.device-orientation
call cordova plugin remove org.apache.cordova.device-motion
call cordova platform remove android
call cordova platform remove ios
call cordova platform add android
call cordova platform add ios
call cordova plugin add org.apache.cordova.geolocation
call cordova plugin add org.apache.cordova.camera
call cordova plugin add org.apache.cordova.contacts
call cordova plugin add org.apache.cordova.file
call cordova plugin add org.apache.cordova.device
call cordova plugin add org.apache.cordova.device-orientation
call cordova plugin add org.apache.cordova.device-motion