cordova plugin remove org.apache.cordova.geolocation
cordova plugin remove org.apache.cordova.camera
cordova plugin remove org.apache.cordova.contacts
cordova plugin remove org.apache.cordova.file
cordova plugin remove org.apache.cordova.device
cordova plugin remove org.apache.cordova.device-orientation
cordova plugin remove org.apache.cordova.device-motion
cordova platform remove android
cordova platform remove ios
cordova platform add android
cordova platform add ios
cordova plugin add org.apache.cordova.geolocation
cordova plugin add org.apache.cordova.camera
cordova plugin add org.apache.cordova.contacts
cordova plugin add org.apache.cordova.file
cordova plugin add org.apache.cordova.device
cordova plugin add org.apache.cordova.device-orientation
cordova plugin add org.apache.cordova.device-motion